import type { StorefrontLocale } from "@/components/storefront/storefront-provider";

export const uiCopy = {
  uk: {
    delivery: "Heymom - турбота починається тут",
    service: "Оригінальні товари · Турботлива підтримка · Повернення протягом 14 днів",
    categories: "Категорії",
    search: "Пошук по товарах",
    favorites: "В обраному",
    cart: "Кошик",
    home: "Головна",
    catalog: "Каталог",
    quickChoice: "Швидкий вибір",
    popularCategories: "Популярні категорії",
    chooseNeed: "Обирайте за потребою",
    allProducts: "Усі товари",
    sorting: "Сортування",
    defaultSort: "За замовчуванням",
    priceAsc: "Від дешевших",
    priceDesc: "Від дорожчих",
    popularitySort: "За популярністю",
    titleSort: "За назвою",
    inStock: "В наявності",
    outOfStock: "Немає в наявності",
    buy: "Купити",
    unavailable: "Немає",
    back: "До всіх товарів",
    addCart: "Додати до кошика",
    description: "Загальний опис",
    specifications: "Характеристики",
    overview: "Загальна інформація",
    fullDescription: "Опис",
    reviews: "Відгуки",
    availability: "Наявність",
    category: "Категорія",
    heroEyebrow: "Heymom для батьків",
    heroTitle: "Спокій для мами й малюка",
    heroText: "Турботливі рішення для здоров’я, комфорту та щоденних маленьких радощів.",
    heroCta: "Переглянути каталог",
  },
  ru: {
    delivery: "Heymom - забота начинается здесь",
    service: "Оригинальные товары · Заботливая поддержка · Возврат в течение 14 дней",
    categories: "Категории",
    search: "Поиск по товарам",
    favorites: "В избранном",
    cart: "Корзина",
    home: "Главная",
    catalog: "Каталог",
    quickChoice: "Быстрый выбор",
    popularCategories: "Популярные категории",
    chooseNeed: "Выбирайте по потребности",
    allProducts: "Все товары",
    sorting: "Сортировка",
    defaultSort: "По умолчанию",
    priceAsc: "Сначала дешевле",
    priceDesc: "Сначала дороже",
    popularitySort: "По популярности",
    titleSort: "По названию",
    inStock: "В наличии",
    outOfStock: "Нет в наличии",
    buy: "Купить",
    unavailable: "Нет в наличии",
    back: "Ко всем товарам",
    addCart: "Добавить в корзину",
    description: "Общее описание",
    specifications: "Характеристики",
    overview: "Общая информация",
    fullDescription: "Описание",
    reviews: "Отзывы",
    availability: "Наличие",
    category: "Категория",
    heroEyebrow: "Heymom для родителей",
    heroTitle: "Спокойствие для мамы и малыша",
    heroText: "Заботливые решения для здоровья, комфорта и ежедневных маленьких радостей.",
    heroCta: "Смотреть каталог",
  },
} as const;

export const getUiCopy = (locale: StorefrontLocale) => uiCopy[locale];
